//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arabalar
    {
        public int ArabaId { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Ozellik { get; set; }
        public int KM { get; set; }
        public string HGS { get; set; }
        public decimal GunlukTutar { get; set; }
        public int BayiId { get; set; }
    }
}
