//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bayiler
    {
        public int BayiId { get; set; }
        public string Adi { get; set; }
        public string Yetkilisi { get; set; }
        public string BayiAdres { get; set; }
        public string BayiTelefon { get; set; }
        public decimal BayiCiro { get; set; }
    }
}
