//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odemeler
    {
        public int OdemeId { get; set; }
        public decimal OdemeTutar { get; set; }
        public System.DateTime OdemeTarih { get; set; }
        public double VadeFarki { get; set; }
        public int MusteriId { get; set; }
        public int ArabaId { get; set; }
    }
}
