//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentACarContainer : DbContext
    {
        public RentACarContainer()
            : base("name=RentACarContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Musteriler> MusterilerSet { get; set; }
        public virtual DbSet<Odemeler> OdemelerSet { get; set; }
        public virtual DbSet<Arabalar> ArabalarSet { get; set; }
        public virtual DbSet<Bayiler> BayilerSet { get; set; }
    }
}
